chore: Update test to send an email if tests failed

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -23,7 +23,6 @@ jobs:
           token: ${{ github.token }}
           submodules: recursive
 
-      # Setup Gradle and run Build
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
 
@@ -33,7 +32,6 @@ jobs:
       - name: Build app
         run: ./gradlew app:assembleStandardDebug -Pandroid.injected.build.abi=arm64-v8a
 
-      # Run tests
       - name: Run Unit tests
         run: ./gradlew testDebugUnitTest --stacktrace
 
@@ -45,11 +43,10 @@ jobs:
           echo "::error::APK file not found or invalid path: '$APK_PATH'"
             exit 1
           fi
-          echo "Found APK at: $APK_PATH"
-          echo "apk_path=$APK_PATH" >> "$GITHUB_OUTPUT"
 
       # Run UI tests
       - name: Run UI tests
+        id: maestro_tests
         uses: ReactiveCircus/android-emulator-runner@v2.34.0
         with:
           api-level: 36
@@ -59,16 +56,35 @@ jobs:
           disable-animations: true
           emulator-options: -no-snapshot-save -noaudio -no-boot-anim -camera-back none -skin 540x1110
           disk-size: 6G
-          app: ${{ steps.find_apk.outputs.apk_path }}
           script: |
               echo "Installing Maestro"
               curl -fsSL "https://get.maestro.mobile.dev" | bash
-              
-              echo "APK PATH"
-              echo "${{ steps.find_apk.outputs.apk_path }}"
             
               echo "Installing APK"            
               adb install -t "${{ steps.find_apk.outputs.apk_path }}"
               
               echo "Starting UI tests"
-              $HOME/.maestro/bin/maestro test --output report.xml "${{ steps.find_apk.outputs.apk_path }}" -e=ACCOUNT_EMAIL=${{ secrets.UI_TEST_ACCOUNT_EMAIL }} -e=ACCOUNT_PASSWORD=${{ secrets.UI_TEST_ACCOUNT_PASSWORD }} ./maestro/flow/login.yaml ./maestro/flow/writeEmail.yaml ./maestro/flow/logout.yaml
+              if ! $HOME/.maestro/bin/maestro test --format html --output report.html "${{ steps.find_apk.outputs.apk_path }}" -e=ACCOUNT_EMAIL=${{ secrets.UI_TEST_ACCOUNT_EMAIL }} -e=ACCOUNT_PASSWORD=${{ secrets.UI_TEST_ACCOUNT_PASSWORD }} ./maestro/flow/login.yaml ./maestro/flow/writeEmail.yaml ./maestro/flow/logout.yaml
+                echo "Maestro tests failed!"
+                exit 1
+              fi
+
+      - name: Upload Test Report
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: maestro-test-report
+          path: report.html
+
+      - name: Notify on failure
+        if: failure() && steps.maestro_tests.outcome == 'failure'
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: ${{ secrets.SMTP_INFOMANIAK_SERVER }}
+          server_port: ${{ secrets.SMTP_INFOMANIAK_PORT }}
+          body: |
+            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+            Please check the attached report and the workflow logs for details.
+          to: ${{ secrets.SMTP_UI_TEST_REPORT_MAIL_ANDROID }}
+          from: No reply
+          attachments: report.html
