chore: Use another image to runUI tests

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -30,31 +30,64 @@ jobs:
       - name: Clean gradle cache
         run: ./gradlew clean
 
-      - name: Build with Gradle
-        run: ./gradlew build
+      - name: Build app
+        run: ./gradlew app:assembleStandardDebug
 
       # Run UI tests
       - name: Run UI tests
-        run: |
-          echo "Installing Maestro"
+        uses: ReactiveCircus/android-emulator-runner@v2.34.0
+        with:
+          api-level: 36
+          target: google_apis
+          arch: arm64-v8a
+          avd-name: kdrive-test
+          disable-animations: true
+          emulator-options: -no-snapshot-save -noaudio -no-boot-anim -camera-back none -skin 540x1110
+          disk-size: 6G
+          app-path: ""${{ github.workspace }}/app/build/outputs/apk/standard/debug/infomaniak-mail-1.16.5 (11600501)-standard-debug.apk"
+          script: |
+            echo "Current working directory:"
+            pwd
+            
+            echo "Installing Maestro"
 
-          curl -fsSL "https://get.maestro.mobile.dev" | bash
-          export PATH="$PATH":"$HOME/.maestro/bin"
-          
-          echo "Exporting environment variables"
-          export PATH="$PATH":":/Users/runner/Library/Android/sdk/platform-tools"
-          export PATH="$PATH":":/Users/runner/Library/Android/sdk/emulator"
+            curl -fsSL "https://get.maestro.mobile.dev" | bash
+            export PATH="$PATH":"$HOME/.maestro/bin"
+            
+            echo "github workspace = ${{ github.workspace }}"
 
-          APK_SEARCH_DIR="app/build/outputs/apk/standard/debug"
-          APP_APK_PATH=$(find "$APK_SEARCH_DIR" -maxdepth 1 -type f -name "*.apk" | head -n 1)
+            APK_SEARCH_DIR="${{ github.workspace }}/app/build/outputs/apk/standard/debug"
+            echo "APK_SEARCH_DIR = $APK_SEARCH_DIR"
+            APP_APK_PATH=$(find "$APK_SEARCH_DIR" -maxdepth 1 -type f -name "*.apk" | head -n 1)
+            echo "APP_APK_PATH = $APP_APK_PATH"
+            
+            echo "Files in folder"
+            
+            echo "Files in /Users/runner/actions-runner/_work/android-kMail/android-kMail/"
+             ls -la "/Users/runner/actions-runner/_work/android-kMail/android-kMail/"
+            
+             echo "Files in /Users/runner/actions-runner/_work/android-kMail/android-kMail/app/"
+             ls -la "/Users/runner/actions-runner/_work/android-kMail/android-kMail/app/"
+            
+             echo "Files in /Users/runner/actions-runner/_work/android-kMail/android-kMail/app/build/"
+             ls -la "/Users/runner/actions-runner/_work/android-kMail/android-kMail/app/build/"
+            
+             echo "Files in /Users/runner/actions-runner/_work/android-kMail/android-kMail/app/build/outputs/"
+             ls -la "/Users/runner/actions-runner/_work/android-kMail/android-kMail/app/build/outputs/"
+            
+             echo "Files in /Users/runner/actions-runner/_work/android-kMail/android-kMail/app/build/outputs/apk"
+             ls -la "/Users/runner/actions-runner/_work/android-kMail/android-kMail/app/build/outputs/apk/"
+            
+             echo "Files in /Users/runner/actions-runner/_work/android-kMail/android-kMail/app/build/outputs/apk/standard"
+             ls -la "/Users/runner/actions-runner/_work/android-kMail/android-kMail/app/build/outputs/apk/standard/"
+            
+            echo "Files in /Users/runner/actions-runner/_work/android-kMail/android-kMail/app/build/outputs/apk/standard/debug"
+            ls -la "/Users/runner/actions-runner/_work/android-kMail/android-kMail/app/build/outputs/apk/standard/debug"
 
-          if [ ! -f "$APP_APK_PATH" ]; then
-            echo "APK not found at $APP_APK_PATH"
-            exit 1
-          fi
-                    
-          echo "Installing $APP_APK_PATH on emulator"
-          adb install "$APP_APK_PATH"
-          
-          echo "Starting UI tests"
-          maestro test --output report.xml "$APP_APK_PATH" -e=ACCOUNT_EMAIL=${{ secrets.UI_TEST_ACCOUNT_EMAIL }} -e=ACCOUNT_PASSWORD=${{ secrets.UI_TEST_ACCOUNT_PASSWORD }} ./maestro/flow/login.yaml ./maestro/flow/writeEmail.yaml ./maestro/flow/logout.yaml
+            if [ ! -f "$APP_APK_PATH" ]; then
+              echo "APK not found at $APP_APK_PATH"
+              exit 1
+            fi
+            
+            echo "Starting UI tests"
+            maestro test --output report.xml "$APP_APK_PATH" -e=ACCOUNT_EMAIL=${{ secrets.UI_TEST_ACCOUNT_EMAIL }} -e=ACCOUNT_PASSWORD=${{ secrets.UI_TEST_ACCOUNT_PASSWORD }} ./maestro/flow/login.yaml ./maestro/flow/writeEmail.yaml ./maestro/flow/logout.yaml
