chore: Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -43,6 +43,7 @@ jobs:
           echo "::error::APK file not found or invalid path: '$APK_PATH'"
             exit 1
           fi
+          echo "apk_path=$APK_PATH" >> "$GITHUB_OUTPUT"
 
       # Run UI tests
       - name: Run UI tests
@@ -64,27 +65,23 @@ jobs:
               adb install -t "${{ steps.find_apk.outputs.apk_path }}"
               
               echo "Starting UI tests"
-              if ! $HOME/.maestro/bin/maestro test --format html --output report.html "${{ steps.find_apk.outputs.apk_path }}" -e=ACCOUNT_EMAIL=${{ secrets.UI_TEST_ACCOUNT_EMAIL }} -e=ACCOUNT_PASSWORD=${{ secrets.UI_TEST_ACCOUNT_PASSWORD }} ./maestro/flow/login.yaml ./maestro/flow/writeEmail.yaml ./maestro/flow/logout.yaml
-                echo "Maestro tests failed!"
-                exit 1
-              fi
+              if ! $HOME/.maestro/bin/maestro test --format html --output report.html "${{ steps.find_apk.outputs.apk_path }}" -e=ACCOUNT_EMAIL=${{ secrets.UI_TEST_ACCOUNT_EMAIL }} -e=ACCOUNT_PASSWORD=${{ secrets.UI_TEST_ACCOUNT_PASSWORD }} ./maestro/flow/login.yaml ./maestro/flow/writeEmail.yaml ./maestro/flow/logout.yaml; then echo "Maestro tests failed!"; exit 1; fi
 
       - name: Upload Test Report
-        if: always()
+        if: failure() && steps.maestro_tests.outcome == 'failure'
         uses: actions/upload-artifact@v4
         with:
-          name: maestro-test-report
+          name: test-report
           path: report.html
 
-      - name: Notify on failure
+      - name: Create Github issue with tests failure
         if: failure() && steps.maestro_tests.outcome == 'failure'
-        uses: dawidd6/action-send-mail@v3
+        uses: actions/github-script@v7.0.1
         with:
-          server_address: ${{ secrets.SMTP_INFOMANIAK_SERVER }}
-          server_port: ${{ secrets.SMTP_INFOMANIAK_PORT }}
-          body: |
-            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-            Please check the attached report and the workflow logs for details.
-          to: ${{ secrets.SMTP_UI_TEST_REPORT_MAIL_ANDROID }}
-          from: No reply
-          attachments: report.html
+          script: |
+            await github.rest.issues.create({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              title: 'UI tests failure',
+              body: 'Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.',
+            })
